### ISSUE TITLE
[CT-2798] Automatically open an issue in docs.getdbt.com on labeled PRs

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/actions#111]
### Problem
We are inconsistent with opening associated issues for changes with user facing implications.

### Solution
Set up a GitHub action on the repos that will open a minimal issue in `docs.getdbt.com`.  The action should:

1. Open the new issue only when a specific label (`Docs Needed` or ?) and the PR is merged.  You should also be able to add the label after a PR is merged to get the issue created.
2. Include a link to the related PR in the issue
3. Assign the PR Author to the Issue to add more information
4. Possibly post a comment on the PR with a link to the opened issue.  Since we're putting a link in the issues back to the PR there will be an automatic GitHub update linking the two issues for tracking purposes.  But if we want to include extra info like "Go fill out more details for the docs issue" we could post a comment.  The comment may be ignored by the author though.

This should be a reusable workflow.  We would need to add a simple call to it in any repos we want this functionality.

**Comment by jtcohen6** [comment]
We already have a label for this that we've been using: [`user docs`](https://github.com/dbt-labs/dbt-core/pulls?q=is%3Apr+label%3A%22user+docs%22+)

It would be fantastic if we could automate the opening of a tracking issue, as soon as a labeled PR is merged, linking back to that PR
