### ISSUE TITLE
[CT-2462] Grab Bag Task to Track GHA Deprecation Resolution

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/actions#39]
## High Level Task
Update workflows to remove deprecation warnings.

## Acceptance Criteria
The following repositories have no deprecations.  Note that some of the repos have open PRs to fix some or all of the deprecations and just need to be reviewed.
- [x] https://github.com/dbt-labs/dbt-core/issues/7452
- [x] https://github.com/dbt-labs/dbt-snowflake/issues/577
- [x] https://github.com/dbt-labs/dbt-spark/issues/740
- [x] https://github.com/dbt-labs/dbt-redshift/issues/417
- [x] https://github.com/dbt-labs/dbt-bigquery/issues/678
- [x] https://github.com/dbt-labs/dbt-extractor/issues/63
- [x] https://github.com/dbt-labs/dbt-release/issues/77
- [x] https://github.com/dbt-labs/dbt-rpc/issues/131
- [x] https://github.com/dbt-labs/homebrew-dbt/issues/288
- [x] https://github.com/dbt-labs/hologram/issues/53
- [x] https://github.com/dbt-labs/tree-sitter-jinja2/issues/15
- [x] https://github.com/dbt-labs/actions/issues/93
- [x] https://github.com/dbt-labs/dbt-core-snapshots/issues/18
- [x] https://github.com/dbt-labs/dbt-database-adapter-scaffold/issues/55
- [x] https://github.com/dbt-labs/dbt-server/issues/222

### These are pending some questions and don't contain any outdated node references
- [x] https://github.com/dbt-labs/dbt-docs/issues/415

## Details
`set-output` and (`save-state` but I'm not sure we're using it) will be deprecated 5/31/2023.  We need to update actions appropriately.  This could be do while also centralizing workflows (#38, #23, etc) 

Official Details: [GitHub Actions: Deprecating save-state and set-output commands | GitHub Changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

Also node16 by 9/1/2023

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

This will require looking at the workflows and actions we reference.  Easiest way is to look at logs from workflow outputs as there will be deprecation warnings.

Known culprits:

1. actions/checkout@v2
2. actions/download-artifact@v2
3. actions/upload-artifact@v2
4. actions/setup-python
5. definitely more

All relevant changes to backport will be tracked in #730

**Comment by emmyoop** [comment]
All these changes are going to need to be backported because we run a lot of actions off *.latest branches.

**Comment by davidbloss** [comment]
> sourcegraph is a great tool to find all occurrences of various usages:

☝️ yes!

Note for anybody that might pick up one of these tickets.
On a per-repo basis I am using [rg](https://github.com/BurntSushi/ripgrep#ripgrep-rg) from the command line to get a condensed view of GH actions as I update them.
`rg " uses: " | cut -d ':' -f  3 | sort | uniq`
