### ISSUE TITLE
[CT-1814] [CT-420] Make a GitHub Action that periodically installs dbt in all the supported ways.

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/actions#62]
### Describe the Feature

As a followup to dbt-labs/dbt-core#4891, to reduce the amount of time it takes to recognize installation issues with dbt core, twice daily we should attempt to install dbt core in [all the supported ways](https://docs.getdbt.com/dbt-cli/install/overview) and alert on failures in slack.

#### All Available install methods:
[Use Homebrew to install dbt](https://docs.getdbt.com/docs/get-started/homebrew-install) 
[Use pip to install dbt](https://docs.getdbt.com/docs/get-started/pip-install)
[Use a Docker image to install dbt](https://docs.getdbt.com/docs/get-started/docker-install)
[Install dbt from source](https://docs.getdbt.com/docs/get-started/source-install)

#### Existing Install Testing
Scheduled testing of Homebrew install [here](https://github.com/dbt-labs/homebrew-dbt/blob/main/.github/workflows/installation-tests.yml)

#### Expected Schedule (same as Homebrew)
`cron: "0 9,13,18 * * *" # 9:00, 13:00, 18:00 UTC`

#### Verify Install with command
`dbt --version`

#### Failures to Slack
Match pattern in Homebrew [installation-tests.yml](https://github.com/dbt-labs/homebrew-dbt/blob/main/.github/workflows/installation-tests.yml)

#### General Design
We should be able to schedule a single workflow to run that calls then a reusable workflow for each test type in a matrix of adapters.  All workflows should also be able to be manually triggered.

#### Priority
1. pip
2. homebrew (done)
3. docker
4. source

#### Related issue
Docker Build Tests - https://github.com/dbt-labs/dbt-core/issues/5154

**Comment by emmyoop** [comment]
This is the issue specific to Docker: https://github.com/dbt-labs/dbt-core/issues/5154

Not much info in it but linking for complete picture

**Comment by emmyoop** [comment]
This is done!
